--- #YAML:1.0
name:               Statistics-TheilSenEstimator
version:            0.05
abstract:           ~
author:
    - jimi <jimi@webu.co.uk>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:                 5.006
    Statistics::QuickMedian:  0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
